services:
  spark-delta:
    build:
      context: spark-delta
      dockerfile: Dockerfile
    container_name: spark-delta
    networks:
      lakehouse_net:
    volumes:
      - type: bind
        source: spark-delta/conf
        target: /opt/spark/conf
    depends_on:
      - minio
      - unity-catalog
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true
  unity-catalog:
    build: 
      context: unity-catalog
    container_name: unity-catalog
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT=true
    depends_on:
      - minio
    networks:
      lakehouse_net:
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: unity-catalog/etc/conf
        target: /app/unitycatalog/etc/conf
      - type: volume
        source: unitycatalog_data
        target: /app/unitycatalog/etc/data
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      lakehouse_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - type: volume
        source: minio_data
        target: /data
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      lakehouse_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
networks:
  lakehouse_net:
volumes:
  minio_data:
  unitycatalog_data: